name: Build and Deploy

on:
    push:
        branches:
            master

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22.8.0'
            - name: Install clasp
              run: npm install -g @google/clasp
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install project dependencies
              run: npm install
            - name: Generate .clasprc.json
              run: |
                echo '{
                    "token": {
                    "access_token": "'${{ secrets.ACCESS_TOKEN }}'",
                    "scope": "https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/script.webapp.deploy openid https://www.googleapis.com/auth/userinfo.email",
                    "token_type": "Bearer",
                    "id_token": "'${{ secrets.ID_TOKEN }}'",
                    "refresh_token": "'${{ secrets.REFRESH_TOKEN }}'"
                    },
                    "oauth2ClientSettings": {
                    "clientId": "'${{ secrets.CLIENT_ID }}'",
                    "clientSecret": "'${{ secrets.CLIENT_SECRET }}'",
                    "redirectUri": "http://localhost"
                    },
                    "isLocalCreds": false
                }' > ~/.clasprc.json
            - name: Generate .clasp.json
              run: |
                echo '{
                    "scriptId": "'${{ secrets.SCRIPT_ID }}'",
                    "rootDir": "./build"
                }' > .clasp.json
            - name: Build and Deploy
              run: npm run deploy:prod