name: Test

on:
    pull_request:
        types: [ opened, synchronize ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22.8.0'
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install project dependencies
              run: npm install
            - name: Test
              run: npm run test